### ISSUE TITLE
Incorrect Results for missed classes

### ISSUE THREAD

**Issue by kaustavbhattacharya07** [dsciitbbs/acl#11]
The 'result' dictionary returned in 'missedClassScrapper.py'' should contain a list of values of all the subjects of which classes are missed. Currently only one subject is showing and the rest are overwritten.

**Comment by PalAditya** [comment]
I could not reproduce the results.
Could you attach a screenshot of the same, please? 🤔

**Comment by kaustavbhattacharya07** [comment]
![github_acl1](https://user-images.githubusercontent.com/28350384/67082416-bdabb700-f1b6-11e9-9512-c988815a0d8c.PNG)
![github_acl2](https://user-images.githubusercontent.com/28350384/67082448-cc926980-f1b6-11e9-98ad-d8a25752ba94.PNG)
On 2019-08-14 only Image and Video Processing Attendance is taken into consideration and not that of Digital Control Systems since that it overwritten.
This issue occurs for all the dates.

**Comment by PalAditya** [comment]
@kaustavbhattacharya07 Thanks for this, that part about the json being overwritten is true
@rk36 what do you think?
