### ISSUE TITLE
File for Caching the old data.

### ISSUE THREAD

**Issue by madhavtummala** [dsciitbbs/acl#8]
https://github.com/dsciitbbs/acl/blob/333ae0abfcf35dd5027a0a323bab7c28373eee8d/source/cli.py#L49

https://github.com/dsciitbbs/acl/blob/333ae0abfcf35dd5027a0a323bab7c28373eee8d/source/cli.py#L89

@PalAditya What exactly is the intention behind this line?
File paths in Windows and *Nix are a little different.

The file path points to `/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7\\attendance_past.txt`.
Here first `\` is taken as an escape character and the cache file with the name `3.7\attendance_past.txt` is created at `/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/`.

This is bad for two reasons
1. Need for `sudo` as mentioned in https://github.com/dsciitbbs/acl/pull/4#issuecomment-541839754 only because the file path points to a root location.
2. The cached file should be specific to a user, so it should be stored inside his/her home directory.

I don't think this was the intention in mind while writing the code, although it works as expected.

**Comment by madhavtummala** [comment]
The lines should be changed as `with open(expanduser("~/.attendance_past.txt"), "r") as f:`  
Cache is stored as a hidden file in home directory of the user.  

It works in macOS and the application can be used without root privileges.
Please look into necessary changes to make it work in Windows (if we are providing support for it).

**Comment by PalAditya** [comment]
Well, that definitely doesn't work on Windows. However, if your method works on both Linux and MacOS, would you be up for something like this?
```python
import platform

def getFilePath():
    if platform.system() == 'Windows':
        return sys.exec_prefix + "\\attendance_past.txt"
    else:
        return expanduser("~/.attendance_past.txt")
```

and we can change the ```with open``` calls as:

```with open(getFilePath(), "w") as f:```

Thoughts? Is this clean?

**Comment by madhavtummala** [comment]
What is the exact location that `sys.exec_prefix` returns in case of Windows?  
Is it user specific or a root location?

**Comment by PalAditya** [comment]
It's the base installation directory of Python. If user has install permissions to that directory, read/write would also be enabled-in fact, without write permissions, ```acl``` itself won't be installed

**Comment by madhavtummala** [comment]
In case of Windows, it is a better practice to have a folder `Documents/acl` for our application related files. I have seen a lot of applications follow that. 
If there is no problem with permissions on Windows, we could go with the existing path.

**Comment by madhavtummala** [comment]
> Well, that definitely doesn't work on Windows. However, if your method works on both Linux and MacOS, would you be up for something like this?
> 
> ```python
> import platform
> 
> def getFilePath():
>     if platform.system() == 'Windows':
>         return sys.exec_prefix + "\\attendance_past.txt"
>     else:
>         return expanduser("~/.attendance_past.txt")
> ```
> 
> and we can change the `with open` calls as:
> 
> `with open(getFilePath(), "w") as f:`
> 
> Thoughts? Is this clean?

Yeah, fine. 👍

**Comment by PalAditya** [comment]
> The lines should be changed as `with open(expanduser("~/.attendance_past.txt"), "r") as f:`
> Cache is stored as a hidden file in home directory of the user.
> 
> It works in macOS and the application can be used without root privileges.
> Please look into necessary changes to make it work in Windows (if we are providing support for it).

Apologies. I was using the ```expanduser``` function incorrectly, and it appears that it works in Windows as well.
However, the . infront of it's name doesn't make it hidden in Windows, so should we go for that functionality or not? In that case, we need to add these extra lines after the write function:

```python
import win32con, win32api
file = expanduser("~/.attendance_past.txt") 
win32api.SetFileAttributes(file, win32con.FILE_ATTRIBUTE_HIDDEN)
```
(with a check for whether we are in Windows or not, maybe with ```try/except```). Thoughts please?

**Comment by madhavtummala** [comment]
👍 This works.
Update your fork first, and then create a pull request.
